# トレーディングシステムの設定

# データ設定
data:
  data_dir: "data/spot/monthly/klines"  # データディレクトリのパス
  symbol: "SUIUSDT"  # 取引対象の銘柄
  timeframe: "4h"    # 時間足 (1m, 5m, 15m, 1h, 4h, 1d)
  start: "2020-12-30"  # データ開始日 (YYYY-MM-DD)
  end: "2024-11-30"    # データ終了日 (YYYY-MM-DD)

# ポジションサイズ設定
position_sizing:
  name: "FixedRatioPositionSizing"  # ポジションサイズ計算方法
  params:
    ratio: 0.99  # 資金に対する割合

# バックテスト設定
backtest:
  initial_balance: 10000.0  # 初期資金
  commission: 0.001        # 手数料率
  max_positions: 1         # 同時保有可能な最大ポジション数

# ポジション設定
position:
  ratio: 0.99
  leverage: 1
  initial_balance: 10000
  commission_rate: 0.001

# 最適化設定
optimization:
  enabled: true
  metric: "alpha_score"
  n_trials: 100
  n_jobs: -1
  timeout: null
  strategy_class: "SupertrendRsiChopStrategy"

# ウォークフォワードテスト設定
walkforward:
  enabled: true          # ウォークフォワードテストを行うかどうか
  training_days: 360      # トレーニング期間（日数）
  testing_days: 180       # テスト期間（日数）
  min_trades: 15         # 最小トレード数

# モンテカルロシミュレーション設定
montecarlo:
  enabled: false          # モンテカルロシミュレーションを行うかどうか
  num_simulations: 20000   # シミュレーション回数

# ログ設定
logging:
  level: "INFO"          # ログレベル (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "ttf.log"        # ログファイル名
