# トレーディングシステムの設定

# データ設定
data:
  data_dir: "data/spot/monthly/klines"  # データディレクトリのパス
  symbol: "SUIUSDT"  # 取引対象の銘柄
  timeframe: "4h"    # 時間足 (1m, 5m, 15m, 1h, 4h, 1d)
  start: "2017-10-30"  # データ開始日 (YYYY-MM-DD)
  end: "2025-12-30"    # データ終了日 (YYYY-MM-DD)

# Binanceデータ設定
binance_data:
  data_dir: "data/binance"
  enabled: true
  symbol: "LUNA"
  market_type: "spot"  # spot or future
  timeframe: "4h"
  start: "2000-01-01"
  end: "2124-12-31"

# ポジションサイズ設定
position_sizing:
  ratio: 0.2  # 資金に対する割合
  leverage: 1
  initial_balance: 10000
  commission_rate: 0.001

# バックテスト設定
backtest:
  initial_balance: 10000.0  # 初期資金
  commission: 0.001        # 手数料率
  max_positions: 1         # 同時保有可能な最大ポジション数


# 最適化設定
optimization:
  enabled: true
  metric: "alpha_score"
  n_trials: 500
  n_jobs: -1
  timeout: null
  strategy_class: "SupertrendRsiChopStrategy"

# ウォークフォワードテスト設定
walkforward:
  enabled: true          # ウォークフォワードテストを行うかどうか
  training_days: 360      # トレーニング期間（日数）
  testing_days: 180       # テスト期間（日数）
  min_trades: 15         # 最小トレード数

# モンテカルロシミュレーション設定
montecarlo:
  enabled: false          # モンテカルロシミュレーションを行うかどうか
  num_simulations: 2000   # シミュレーション回数

# ログ設定
logging:
  level: "INFO"          # ログレベル (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "ttf.log"        # ログファイル名

# Supreme Breakout Channel設定（人類史上最強ブレイクアウトチャネル）
sbc_params:
  # 核心パラメータ
  atr_period: 14              # ATR計算期間
  base_multiplier: 2.0        # 基本チャネル幅倍率
  
  # フィルタリングパラメータ
  kalman_process_noise: 0.01  # カルマンフィルタープロセスノイズ
  
  # シグナルパラメータ
  min_strength_threshold: 0.25   # 最小トレンド強度しきい値（0-1）
  min_confidence_threshold: 0.3  # 最小信頼度しきい値（0-1）
  
  # データソース
  src_type: "hlc3"            # 価格ソースタイプ（hlc3, close, hl2など）

# QFAVC設定（Quantum-Fractal Adaptive Volatility Channel）
qfavc_params:
  # 基本パラメータ
  quantum_window: 21
  fractal_window: 34
  flow_window: 21
  garch_window: 55
  
  # 動的期間決定用
  use_dynamic_periods: true
  dc_detector_type: "dudi_e"
  dc_cycle_part: 0.4
  
  # ボラティリティパラメータ
  base_multiplier: 2.0
  garch_alpha: 0.1
  garch_beta: 0.85
  
  # カルマンフィルターパラメータ
  kalman_process_noise: 0.01
  
  # データソース
  src_type: "hlc3"
  volume_src: "volume"

# テスト設定
test_configuration:
  enable_performance_test: true
  enable_quantum_test: true
  enable_fractal_test: true
  enable_visualization: true
  generate_report: true

# Ultimate Volatility State設定
ultimate_volatility_state:
  # 基本パラメータ
  period: 21                     # 基本期間
  threshold: 0.5                 # 高/低ボラティリティの閾値 (0.0-1.0)
  zscore_period: 50              # Z-Score計算期間
  src_type: "hlc3"               # 価格ソース
  smoother_period: 5             # スムージング期間
  adaptive_threshold: true       # 適応的閾値調整
  
  # 表示設定
  chart_title: "Ultimate Volatility State Analysis"
  high_vol_color: "red"          # 高ボラティリティ色
  low_vol_color: "blue"          # 低ボラティリティ色
  probability_color: "orange"    # 確率ライン色
  
  # 出力設定
  save_chart: true
  chart_filename: "ultimate_volatility_state_analysis"
  show_components: true          # コンポーネント表示

# Enhanced Trend State設定
enhanced_trend_state:
  # 基本パラメータ
  base_period: 20                # 基本期間
  threshold: 0.42                # トレンド判定閾値 (V2最適値)
  src_type: "hlc3"              # 価格ソース
  
  # 機能設定
  use_dynamic_period: true       # 動的期間調整
  volatility_adjustment: true    # ボラティリティ調整
  atr_smoothing: true           # ATRスムージング
  
  # 重み設定
  er_weight: 0.55               # 効率比の重み（V2最適値）
  chop_weight: 0.45             # チョピネス指数の重み（V2最適値）
  
  # サイクル検出器設定
  detector_type: "absolute_ultimate"  # サイクル検出器タイプ
  max_cycle: 50                 # 最大サイクル
  min_cycle: 8                  # 最小サイクル
  
  # 表示設定
  chart_title: "Enhanced Trend State Analysis"
  trend_color: "green"          # トレンド色
  range_color: "red"            # レンジ色
  composite_color: "purple"     # 複合スコア色
  confidence_color: "orange"    # 信頼度色
  
  # 出力設定
  save_chart: true
  chart_filename: "enhanced_trend_state_analysis"
  show_components: true         # コンポーネント表示

# 出力設定
output_settings:
  chart_filename: "qfavc_analysis"
  report_filename: "qfavc_performance_report"
