# トレーディングシステムの設定

# データ設定
data:
  data_dir: "data/spot/monthly/klines"  # データディレクトリのパス
  symbol: "SUIUSDT"  # 取引対象の銘柄
  timeframe: "4h"    # 時間足 (1m, 5m, 15m, 1h, 4h, 1d)
  start: "2017-10-30"  # データ開始日 (YYYY-MM-DD)
  end: "2025-12-30"    # データ終了日 (YYYY-MM-DD)

# Binanceデータ設定
binance_data:
  data_dir: "data/binance"
  enabled: true
  symbol: "AVAX"
  market_type: "spot"  # spot or future
  timeframe: "4h"
  start: "2000-01-01"
  end: "2124-12-31"

# ポジションサイズ設定
position_sizing:
  ratio: 0.2  # 資金に対する割合
  leverage: 1
  initial_balance: 10000
  commission_rate: 0.001

# バックテスト設定
backtest:
  initial_balance: 10000.0  # 初期資金
  commission: 0.001        # 手数料率
  max_positions: 1         # 同時保有可能な最大ポジション数


# 最適化設定
optimization:
  enabled: true
  metric: "alpha_score"
  n_trials: 500
  n_jobs: -1
  timeout: null
  strategy_class: "SupertrendRsiChopStrategy"

# ウォークフォワードテスト設定
walkforward:
  enabled: true          # ウォークフォワードテストを行うかどうか
  training_days: 360      # トレーニング期間（日数）
  testing_days: 180       # テスト期間（日数）
  min_trades: 15         # 最小トレード数

# モンテカルロシミュレーション設定
montecarlo:
  enabled: false          # モンテカルロシミュレーションを行うかどうか
  num_simulations: 2000   # シミュレーション回数

# ログ設定
logging:
  level: "INFO"          # ログレベル (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "ttf.log"        # ログファイル名
