# トレーディングシステムの設定

# データ設定
data:
  data_dir: "data/spot/monthly/klines"  # データディレクトリのパス
  symbol: "SUIUSDT"  # 取引対象の銘柄
  timeframe: "4h"    # 時間足 (1m, 5m, 15m, 1h, 4h, 1d)
  start: "2017-10-30"  # データ開始日 (YYYY-MM-DD)
  end: "2025-12-30"    # データ終了日 (YYYY-MM-DD)

# Binanceデータ設定
binance_data:
  data_dir: "data/binance"
  enabled: true
  symbol: "PEPE"
  market_type: "spot"  # spot or future
  timeframe: "4h"
  start: "2000-01-01"
  end: "2124-12-31"

# ポジションサイズ設定
position_sizing:
  ratio: 0.2  # 資金に対する割合
  leverage: 1
  initial_balance: 10000
  commission_rate: 0.001

# バックテスト設定
backtest:
  initial_balance: 10000.0  # 初期資金
  commission: 0.001        # 手数料率
  max_positions: 1         # 同時保有可能な最大ポジション数


# 最適化設定
optimization:
  enabled: true
  metric: "alpha_score"
  n_trials: 500
  n_jobs: -1
  timeout: null
  strategy_class: "SupertrendRsiChopStrategy"

# ウォークフォワードテスト設定
walkforward:
  enabled: true          # ウォークフォワードテストを行うかどうか
  training_days: 360      # トレーニング期間（日数）
  testing_days: 180       # テスト期間（日数）
  min_trades: 15         # 最小トレード数

# モンテカルロシミュレーション設定
montecarlo:
  enabled: false          # モンテカルロシミュレーションを行うかどうか
  num_simulations: 2000   # シミュレーション回数

# ログ設定
logging:
  level: "INFO"          # ログレベル (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "ttf.log"        # ログファイル名

# Supreme Breakout Channel設定（人類史上最強ブレイクアウトチャネル）
sbc_params:
  # 核心パラメータ
  atr_period: 14              # ATR計算期間
  base_multiplier: 2.0        # 基本チャネル幅倍率
  
  # フィルタリングパラメータ
  kalman_process_noise: 0.01  # カルマンフィルタープロセスノイズ
  
  # シグナルパラメータ
  min_strength_threshold: 0.25   # 最小トレンド強度しきい値（0-1）
  min_confidence_threshold: 0.3  # 最小信頼度しきい値（0-1）
  
  # データソース
  src_type: "hlc3"            # 価格ソースタイプ（hlc3, close, hl2など）

# QFAVC設定（Quantum-Fractal Adaptive Volatility Channel）
qfavc_params:
  # 基本パラメータ
  quantum_window: 21
  fractal_window: 34
  flow_window: 21
  garch_window: 55
  
  # 動的期間決定用
  use_dynamic_periods: true
  dc_detector_type: "dudi_e"
  dc_cycle_part: 0.4
  
  # ボラティリティパラメータ
  base_multiplier: 2.0
  garch_alpha: 0.1
  garch_beta: 0.85
  
  # カルマンフィルターパラメータ
  kalman_process_noise: 0.01
  
  # データソース
  src_type: "hlc3"
  volume_src: "volume"

# テスト設定
test_configuration:
  enable_performance_test: true
  enable_quantum_test: true
  enable_fractal_test: true
  enable_visualization: true
  generate_report: true

# 出力設定
output_settings:
  chart_filename: "qfavc_analysis"
  report_filename: "qfavc_performance_report"
